### ISSUE TITLE
Feedback on community letter V0.1

### ISSUE THREAD

**Issue by Poruthoor** [Poruthoor/LearningCurveInitiative#1]
Hi trainees and others,

We are hosting this space as the forum for adding suggestions and feedback for the [community letter V0.1](https://github.com/Poruthoor/NegativeDataInitiative/blob/main/negativeDatainitiative.pdf). Please feel free to write your opinions and comments.

**Comment by VOD555** [comment]
Looks good! I think the community letter is ok to be sent around for more feedback from senior scientists.
Some comments:
Another long-term goal that we can pursue is to provide practical examples for the limitations of specific techniques and we can also share our feedback and suggestions to method forums such as plumed (https://www.plumed.org/forum) or alchemystry wiki (http://alchemistry.org/wiki/).

I'll leave more comments on other issues.

**Comment by Poruthoor** [comment]
> Another long-term goal that we can pursue is to provide practical examples for the limitations of specific techniques and we can also share our feedback and suggestions to method forums such as plumed (https://www.plumed.org/forum) or alchemystry wiki (http://alchemistry.org/wiki/).

@VOD555 Feel free to include these comments in #5?

**Comment by tnozturk** [comment]
It may be necessary to add examples for each category of "otherwise-unpublished" data.  I'm afraid people may understand "limitations of specific techniques" differently too, so examples can help.

**Comment by Poruthoor** [comment]
@tnozturk , I moved your comments to #7 as we decided to add them in the following letter. Since we all agree on this draft, I'm closing this issue. Anyone can reopen this issue for further feedback.
